name: Catalogue CI workflow
on:
  push:
   branches:
   - feature-branch
  workflow_dispatch:
    inputs: 
      project:
        type: string
        required: true
        description: "Enter project name"
      component:
        type: string
        required: true
        description: "Enter component name"
      description:
        type: string
        required: false 
jobs:
  catalogue:
    if: ${{ github.ref != 'refs/heads/main' }}
    uses: nihu-ci/usable-workflow/.github/workflows/shared-nodejs.yaml@main
    permissions:  #controls what gittoken can do
      contents: read
      statuses: write
    with:
      project: ${{ inputs.project || 'roboshop' }}
      component: ${{ inputs.component || 'catalogue' }}